version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booktracker

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    depends_on:
      - postgres

    ports:
      - "5000:5000"

    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_7OmX3PUyRYDK@ep-spring-art-awmp3ia1.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
      JWT_SECRET: my_book_tracker_secret_2026

volumes:
  postgres_data: